---
################################################################################
### Tasks to get all distro relevant information
################################################################################
# ------------------------------------------------------------------------------
- name: Gather OS facts
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!any'
      - distribution
      - distribution_major_version
      - distribution_release
      - distribution_version
# ------------------------------------------------------------------------------
- name: "Set \"distro\" variable (fact)"
  # https://docs.ansible.com/ansible/latest/modules/set_fact_module.html
  set_fact:
    distro: "{{ (ansible_distribution + '-' +  ansible_distribution_version )|lower }}"
  when: 'distro is not defined'
# ------------------------------------------------------------------------------
- name: Include OS-specific variables ({{ distro }})
  include_vars:
    file: "{{ distro }}.yml"
  ignore_errors: yes
# ------------------------------------------------------------------------------
- name: "Current \"distro\" variable"
  # https://docs.ansible.com/ansible/latest/modules/debug_module.html
  debug:
    msg:
      - "Distribution: {{ ansible_distribution }}"
      - "Version: {{ ansible_distribution_version }}"
      - "distro: {{ distro }}"
