---
################################################################################
### Tasks to get all distro relevant information
################################################################################
# ------------------------------------------------------------------------------
- name: Include OS-specific variables ({{ distro }})
  include_vars:
    file: "{{ distro }}.yml"
  ignore_errors: yes
