---
################################################################################
### tasks file for os_facts ####################################################
################################################################################

################################################################################
- name: "Get common \"os\" related information"
  import_tasks: "1-get_common_os_infos.yml"
