---
################################################################################
### tasks file for os_facts ####################################################
################################################################################

################################################################################
### Get distro information (name, version, ...)
################################################################################
- name: "Get \"distro\" related information"
  import_tasks: "1_get-common-distro-infos.yml"
