---
################################################################################
### tasks file for os_facts ####################################################
################################################################################

################################################################################
### Get distro information (name, version, ...)
################################################################################
- name: "Get common \"os\" related information"
  import_tasks: "1_get-common-os-infos.yml"
- name: "Get common \"os\" related information"
  import_tasks: "2_get-specific-os-infos.yml"
