---
# tasks file for git_repo_manager
################################################################################

#-------------------------------------------------------------------------------
- name: "Render template {{ git_repositories_file }}.j2"
  template:
    src: "{{ git_repositories_file }}.j2"
    dest: "/tmp/{{ git_repositories_file }}.yml"
    force: yes
  delegate_to: localhost
- name: Include vars from "/tmp/{{ git_repositories_file }}.yml"
  include_vars:
    file: "/tmp/{{ git_repositories_file }}.yml"
#-------------------------------------------------------------------------------
- name: " Render template {{ git_repo_symlinks }}.j2"
  template:
    src: "{{ git_repo_symlinks }}.j2"
    dest: "/tmp/{{ git_repo_symlinks }}.yml"
    force: yes
  delegate_to: localhost
- name: Include vars from "/tmp/{{ git_repo_symlinks }}.yml"
  include_vars:
    file: "/tmp/{{ git_repo_symlinks }}.yml"
#-------------------------------------------------------------------------------
- name: Install git on {{ distro }}
  block:
    - name: 'Install git on "Darwin" based OS'
      community.general.homebrew:
        name: git
        state: latest
      when: ansible_os_family == "Darwin"
      tags: git_installation
    - name: 'Install git on "Linux" based OS'
      ansible.builtin.package:
        name: git
        state: latest
      when: ansible_os_family != "Darwin"
      tags: git_installation

  rescue:
    - name: "Failure: Install git on {{ distro }}"
      ansible.builtin.debug:
        msg: |
          Failed to install git.
          Please check, if the system is supported and package manager is
          available.
#-------------------------------------------------------------------------------
- name: Check git directory structure
  block:
    - name: Assert "git_base_dir" is defined and stop playbook if not
      ansible.builtin.assert:
        that:
          - git_base_dir is defined
        fail_msg: "Variable 'git_base_dir' is not defined."
        success_msg: "Variable 'git_base_dir' is defined: '{{ git_base_dir }}'"

    - name: Ensure directories from 'git_dirs' variable exist
      ansible.builtin.file:
        path: "{{ item.value }}"
        state: directory
        mode: '0750'
      loop: "{{ git_dirs | dict2items }}"
      register: dir_check

    - name: Print directory check results
      ansible.builtin.debug:
        msg: "{{ item.item.values() | first }} {{ 'created or modified' if item.changed
              else 'already exists' }}."
      loop: "{{ dir_check.results }}"
      loop_control:
        label: "{{ item.item.values() | first }}"
      when: item is changed or item.changed == false

  rescue:
    - name: "Failure: Check git directory structure"
      ansible.builtin.debug:
        msg: |
          git directory structure not available or has failures.
          Please check, git directory structure under {{ git_base_dir }}
#-------------------------------------------------------------------------------
- name: Clone git repositories
  block:
    - name: Clone or pull-rebase git repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        clone: '{{ item.clone | default(true) }}'
        dest: "{{ item.dest }}"
        version: "{{ item.version | default('main') }}"
        verify_commit: "{{ item.verify_commit | default(false) }}"
        update: yes
        force: no
      loop: "{{ git_repositories }}"
      #no_log: true
      ignore_errors: yes

    - name: Set permissions on the cloned directories
      ansible.builtin.file:
        path: "{{ item.dest }}"
        mode: '0750'
      loop: "{{ git_repositories }}"
  tags: git_cloning

  rescue:
    - name: "Failure: Clone git repositories"
      ansible.builtin.debug:
        msg: |
          Cloning git repositories failed.
          Please check, git directory structure under {{ git_base_dir }}
#-------------------------------------------------------------------------------
- name: Manage symlinks
  block:
    - name: Create symlinks for individual directory git_repo structure
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0750'
        state: link
        force: yes
      loop: "{{ all_symlinks }}"
      when: all_symlinks | default([]) | length > 0
