---
# defaults file for git_repo_manager

git_base_dir: "/tmp"

git_dirs:
  - git_base_dir_gh: "{{ git_base_dir }}/gh"
  - git_base_dir_gh_thowdev: "{{ git_base_dir }}/thowdev"
  - git_base_dir_gh_thowdev_private: "{{ git_base_dir }}/thowdev/_private"

git_repositories:
  - name: ac_thow_system_cc
    repo: "git@github.com:thowdev/ac_thow_system_cc.git"
    clone: yes
    dest: "{{ git_base_dir_gh_thowdev }}/ac_thow_system_cc"
    verify_commit: yes
    version: main
    forked: no
